version: '2'
services:
  mariadb:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=128M
    volumes: 
      - "./mariadb:/var/lib/mysql:rw"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"