apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: myproj-api
  name: myproj-api
spec:
  ports:
  - name: "5057"
    port: 5057
    targetPort: 5057
  selector:
    io.kompose.service: myproj-api
status:
  loadBalancer: {}
