apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: myproj-worker
  name: myproj-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: myproj-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: myproj-worker
    spec:
      containers:
      - args:
        - rq
        - worker
        - --url
        - redis://myproj_redis:6379/1
        - my_api_queue
        image: myproj:latest
        imagePullPolicy: ""
        name: myproj-worker
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
