apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: myproj-redis
  name: myproj-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: myproj-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: myproj-redis
    spec:
      containers:
      - image: redis:4.0.6-alpine
        imagePullPolicy: ""
        name: myproj-redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: myproj-redis-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: myproj-redis-claim0
        persistentVolumeClaim:
          claimName: myproj-redis-claim0
status: {}
